version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_planora
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222" #port for client
      - "8222:8222" #port for monitoring
    command: ["-js", "-m", "8222"]
    restart: unless-stopped

volumes:
  postgres_data:
